project:
  type: website
  output-dir: docs

website:
  title: "jadenorli"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - photography.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

