---
title: "Photography"
format:
  html:
    page-layout: full
    css:
      - styles.css
      - fancybox/css/fancybox.css
    includes:
      in-header: |
        <script src="fancybox/js/fancybox.umd.js"></script>
        <script>
          document.addEventListener("DOMContentLoaded", function() {
            if (window.Fancybox) {
              Fancybox.bind("[data-fancybox]", {
                Thumbs: false,
                Toolbar: true
              });
              console.log("✅ Fancybox bound.");
            } else {
              console.error("❌ Fancybox failed to load.");
            }
          });
        </script>
---





```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(here)
library(tidyverse)

source(here("scripts", "render_gallery.R"))
source(here("scripts", "generate_metadata.R"))

```


```{r}
generate_metadata(category = "terrestrial")
```


# Marine Photography

```{r, echo=FALSE, results='asis'}
render_gallery(
  category = "marine",
  metadata_file = here("data", "marine_metadata.csv")
)
```


```{r, echo=FALSE, results='asis'}
render_gallery(
  category = "terrestrial",
  metadata_file = here("data", "terrestrial_metadata.csv")
)
```
